Task 2. Finite automatons building
Ixorlive/formal-lang-course pull request #2
Opened 2023-03-02 00:27 UTC by Ixorlive

**File project/fa_building.py**

- Implemented the build_minimal_dfa_by_regex method, which builds a minimal Deterministic Finite Automaton (DFA) from a regular expression using the Regex::to_epsilon_nfa() and to_deterministic() methods.
- Implemented the build_nfa_from_graph method, which builds a non-deterministic finite automaton (NFA) from a graph using the add_transition() method. It allows setting start and finale states, although by default all vertices are considered start and finale states.

**File tests/test_fa_build.py**
Wrote simple tests to check the correctness of the implemented methods. Specifically:

- For the build_minimal_dfa_by_regex method, checked that the regular expressions "a*b*" and "a (b|c)* d" result in the expected minimal DFAs.
- For the build_nfa_from_graph method, tested on a simple graph with and without explicitly setting start and finale states. Also verified that the method builds an NFA and not a DFA.

2023-03-02 06:34 UTC, rustam-azimov requested changes

2023-03-02 06:34 UTC, rustam-azimov commented on project/fa_building.py
> +    dfa = nfa.to_deterministic()
Проверьте документацию библиотеки. Тут лишняя строчка есть

2023-03-02 11:48 UTC, Ixorlive commented
Удалил to_deterministic()

2023-03-03 08:03 UTC, rustam-azimov approved these changes

2023-03-03 09:44 UTC, merged